version: '3'
services:
  rsc:
    build: rsc
    container_name: rsc
    ports:
      - "5000:5000"
    volumes:
      - rsc:/code/Resources
  jwt:
    build: jwt
    container_name: jwt
  usr:
      build: usr
      container_name: usr
      ports:
        - "5001:5000"
  bd:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27016:27017"
    volumes:
      - DBdata:/data/db
volumes:
  DBdata:
  rsc: