version: '3'
services:
  rsc:
    build: rsc
    container_name: rsc
    ports:
      - "5000:5000"
    volumes:
      - rsc:/code/Resources
    environment:
      DOC_PASS: changeit
  jwt:
    build: jwt
    container_name: jwt
    environment:
      JWT_PASS: changeit
  usr:
      build: usr
      container_name: usr
      ports:
        - "5001:5000"
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - DBdata:/data/db
volumes:
  DBdata:
  rsc:
